spring:
    application:
        name: grpc-customer-example
    output:
        ansi:
            enabled: always

management.endpoints.web.exposure.include: metrics
management.endpoint.metrics.enabled: true