// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

// Protobuf Java Version: 3.25.1
package br.example.demo.model;

public final class ProductProto {
  private ProductProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProductOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.Product)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * Protobuf type {@code model.Product}
   */
  public static final class Product extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.Product)
      ProductOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Product.newBuilder() to construct.
    private Product(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Product() {
      name_ = "";
      description_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Product();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.example.demo.model.ProductProto.internal_static_model_Product_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.example.demo.model.ProductProto.internal_static_model_Product_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.example.demo.model.ProductProto.Product.class, br.example.demo.model.ProductProto.Product.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object description_ = "";
    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.example.demo.model.ProductProto.Product)) {
        return super.equals(obj);
      }
      br.example.demo.model.ProductProto.Product other = (br.example.demo.model.ProductProto.Product) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.example.demo.model.ProductProto.Product parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.example.demo.model.ProductProto.Product parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.example.demo.model.ProductProto.Product parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.example.demo.model.ProductProto.Product parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.example.demo.model.ProductProto.Product parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.example.demo.model.ProductProto.Product parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.example.demo.model.ProductProto.Product parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.example.demo.model.ProductProto.Product parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static br.example.demo.model.ProductProto.Product parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static br.example.demo.model.ProductProto.Product parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.example.demo.model.ProductProto.Product parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.example.demo.model.ProductProto.Product parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.example.demo.model.ProductProto.Product prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.Product}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.Product)
        br.example.demo.model.ProductProto.ProductOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.example.demo.model.ProductProto.internal_static_model_Product_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.example.demo.model.ProductProto.internal_static_model_Product_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.example.demo.model.ProductProto.Product.class, br.example.demo.model.ProductProto.Product.Builder.class);
      }

      // Construct using br.example.demo.model.ProductProto.Product.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        name_ = "";
        description_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.example.demo.model.ProductProto.internal_static_model_Product_descriptor;
      }

      @java.lang.Override
      public br.example.demo.model.ProductProto.Product getDefaultInstanceForType() {
        return br.example.demo.model.ProductProto.Product.getDefaultInstance();
      }

      @java.lang.Override
      public br.example.demo.model.ProductProto.Product build() {
        br.example.demo.model.ProductProto.Product result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public br.example.demo.model.ProductProto.Product buildPartial() {
        br.example.demo.model.ProductProto.Product result = new br.example.demo.model.ProductProto.Product(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(br.example.demo.model.ProductProto.Product result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.description_ = description_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.example.demo.model.ProductProto.Product) {
          return mergeFrom((br.example.demo.model.ProductProto.Product)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.example.demo.model.ProductProto.Product other) {
        if (other == br.example.demo.model.ProductProto.Product.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                description_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 3;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        description_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        description_ = getDefaultInstance().getDescription();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        description_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:model.Product)
    }

    // @@protoc_insertion_point(class_scope:model.Product)
    private static final br.example.demo.model.ProductProto.Product DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.example.demo.model.ProductProto.Product();
    }

    public static br.example.demo.model.ProductProto.Product getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Product>
        PARSER = new com.google.protobuf.AbstractParser<Product>() {
      @java.lang.Override
      public Product parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Product> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Product> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public br.example.demo.model.ProductProto.Product getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProductsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.Products)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .model.Product product = 1;</code>
     */
    java.util.List<br.example.demo.model.ProductProto.Product> 
        getProductList();
    /**
     * <code>repeated .model.Product product = 1;</code>
     */
    br.example.demo.model.ProductProto.Product getProduct(int index);
    /**
     * <code>repeated .model.Product product = 1;</code>
     */
    int getProductCount();
    /**
     * <code>repeated .model.Product product = 1;</code>
     */
    java.util.List<? extends br.example.demo.model.ProductProto.ProductOrBuilder> 
        getProductOrBuilderList();
    /**
     * <code>repeated .model.Product product = 1;</code>
     */
    br.example.demo.model.ProductProto.ProductOrBuilder getProductOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code model.Products}
   */
  public static final class Products extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.Products)
      ProductsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Products.newBuilder() to construct.
    private Products(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Products() {
      product_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Products();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.example.demo.model.ProductProto.internal_static_model_Products_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.example.demo.model.ProductProto.internal_static_model_Products_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.example.demo.model.ProductProto.Products.class, br.example.demo.model.ProductProto.Products.Builder.class);
    }

    public static final int PRODUCT_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<br.example.demo.model.ProductProto.Product> product_;
    /**
     * <code>repeated .model.Product product = 1;</code>
     */
    @java.lang.Override
    public java.util.List<br.example.demo.model.ProductProto.Product> getProductList() {
      return product_;
    }
    /**
     * <code>repeated .model.Product product = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends br.example.demo.model.ProductProto.ProductOrBuilder> 
        getProductOrBuilderList() {
      return product_;
    }
    /**
     * <code>repeated .model.Product product = 1;</code>
     */
    @java.lang.Override
    public int getProductCount() {
      return product_.size();
    }
    /**
     * <code>repeated .model.Product product = 1;</code>
     */
    @java.lang.Override
    public br.example.demo.model.ProductProto.Product getProduct(int index) {
      return product_.get(index);
    }
    /**
     * <code>repeated .model.Product product = 1;</code>
     */
    @java.lang.Override
    public br.example.demo.model.ProductProto.ProductOrBuilder getProductOrBuilder(
        int index) {
      return product_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < product_.size(); i++) {
        output.writeMessage(1, product_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < product_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, product_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.example.demo.model.ProductProto.Products)) {
        return super.equals(obj);
      }
      br.example.demo.model.ProductProto.Products other = (br.example.demo.model.ProductProto.Products) obj;

      if (!getProductList()
          .equals(other.getProductList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getProductCount() > 0) {
        hash = (37 * hash) + PRODUCT_FIELD_NUMBER;
        hash = (53 * hash) + getProductList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.example.demo.model.ProductProto.Products parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.example.demo.model.ProductProto.Products parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.example.demo.model.ProductProto.Products parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.example.demo.model.ProductProto.Products parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.example.demo.model.ProductProto.Products parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.example.demo.model.ProductProto.Products parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.example.demo.model.ProductProto.Products parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.example.demo.model.ProductProto.Products parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static br.example.demo.model.ProductProto.Products parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static br.example.demo.model.ProductProto.Products parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.example.demo.model.ProductProto.Products parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.example.demo.model.ProductProto.Products parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.example.demo.model.ProductProto.Products prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.Products}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.Products)
        br.example.demo.model.ProductProto.ProductsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.example.demo.model.ProductProto.internal_static_model_Products_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.example.demo.model.ProductProto.internal_static_model_Products_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.example.demo.model.ProductProto.Products.class, br.example.demo.model.ProductProto.Products.Builder.class);
      }

      // Construct using br.example.demo.model.ProductProto.Products.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (productBuilder_ == null) {
          product_ = java.util.Collections.emptyList();
        } else {
          product_ = null;
          productBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.example.demo.model.ProductProto.internal_static_model_Products_descriptor;
      }

      @java.lang.Override
      public br.example.demo.model.ProductProto.Products getDefaultInstanceForType() {
        return br.example.demo.model.ProductProto.Products.getDefaultInstance();
      }

      @java.lang.Override
      public br.example.demo.model.ProductProto.Products build() {
        br.example.demo.model.ProductProto.Products result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public br.example.demo.model.ProductProto.Products buildPartial() {
        br.example.demo.model.ProductProto.Products result = new br.example.demo.model.ProductProto.Products(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(br.example.demo.model.ProductProto.Products result) {
        if (productBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            product_ = java.util.Collections.unmodifiableList(product_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.product_ = product_;
        } else {
          result.product_ = productBuilder_.build();
        }
      }

      private void buildPartial0(br.example.demo.model.ProductProto.Products result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.example.demo.model.ProductProto.Products) {
          return mergeFrom((br.example.demo.model.ProductProto.Products)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.example.demo.model.ProductProto.Products other) {
        if (other == br.example.demo.model.ProductProto.Products.getDefaultInstance()) return this;
        if (productBuilder_ == null) {
          if (!other.product_.isEmpty()) {
            if (product_.isEmpty()) {
              product_ = other.product_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureProductIsMutable();
              product_.addAll(other.product_);
            }
            onChanged();
          }
        } else {
          if (!other.product_.isEmpty()) {
            if (productBuilder_.isEmpty()) {
              productBuilder_.dispose();
              productBuilder_ = null;
              product_ = other.product_;
              bitField0_ = (bitField0_ & ~0x00000001);
              productBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getProductFieldBuilder() : null;
            } else {
              productBuilder_.addAllMessages(other.product_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                br.example.demo.model.ProductProto.Product m =
                    input.readMessage(
                        br.example.demo.model.ProductProto.Product.parser(),
                        extensionRegistry);
                if (productBuilder_ == null) {
                  ensureProductIsMutable();
                  product_.add(m);
                } else {
                  productBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<br.example.demo.model.ProductProto.Product> product_ =
        java.util.Collections.emptyList();
      private void ensureProductIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          product_ = new java.util.ArrayList<br.example.demo.model.ProductProto.Product>(product_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          br.example.demo.model.ProductProto.Product, br.example.demo.model.ProductProto.Product.Builder, br.example.demo.model.ProductProto.ProductOrBuilder> productBuilder_;

      /**
       * <code>repeated .model.Product product = 1;</code>
       */
      public java.util.List<br.example.demo.model.ProductProto.Product> getProductList() {
        if (productBuilder_ == null) {
          return java.util.Collections.unmodifiableList(product_);
        } else {
          return productBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .model.Product product = 1;</code>
       */
      public int getProductCount() {
        if (productBuilder_ == null) {
          return product_.size();
        } else {
          return productBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .model.Product product = 1;</code>
       */
      public br.example.demo.model.ProductProto.Product getProduct(int index) {
        if (productBuilder_ == null) {
          return product_.get(index);
        } else {
          return productBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .model.Product product = 1;</code>
       */
      public Builder setProduct(
          int index, br.example.demo.model.ProductProto.Product value) {
        if (productBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductIsMutable();
          product_.set(index, value);
          onChanged();
        } else {
          productBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .model.Product product = 1;</code>
       */
      public Builder setProduct(
          int index, br.example.demo.model.ProductProto.Product.Builder builderForValue) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          product_.set(index, builderForValue.build());
          onChanged();
        } else {
          productBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.Product product = 1;</code>
       */
      public Builder addProduct(br.example.demo.model.ProductProto.Product value) {
        if (productBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductIsMutable();
          product_.add(value);
          onChanged();
        } else {
          productBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .model.Product product = 1;</code>
       */
      public Builder addProduct(
          int index, br.example.demo.model.ProductProto.Product value) {
        if (productBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductIsMutable();
          product_.add(index, value);
          onChanged();
        } else {
          productBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .model.Product product = 1;</code>
       */
      public Builder addProduct(
          br.example.demo.model.ProductProto.Product.Builder builderForValue) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          product_.add(builderForValue.build());
          onChanged();
        } else {
          productBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.Product product = 1;</code>
       */
      public Builder addProduct(
          int index, br.example.demo.model.ProductProto.Product.Builder builderForValue) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          product_.add(index, builderForValue.build());
          onChanged();
        } else {
          productBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.Product product = 1;</code>
       */
      public Builder addAllProduct(
          java.lang.Iterable<? extends br.example.demo.model.ProductProto.Product> values) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, product_);
          onChanged();
        } else {
          productBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .model.Product product = 1;</code>
       */
      public Builder clearProduct() {
        if (productBuilder_ == null) {
          product_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          productBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .model.Product product = 1;</code>
       */
      public Builder removeProduct(int index) {
        if (productBuilder_ == null) {
          ensureProductIsMutable();
          product_.remove(index);
          onChanged();
        } else {
          productBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .model.Product product = 1;</code>
       */
      public br.example.demo.model.ProductProto.Product.Builder getProductBuilder(
          int index) {
        return getProductFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .model.Product product = 1;</code>
       */
      public br.example.demo.model.ProductProto.ProductOrBuilder getProductOrBuilder(
          int index) {
        if (productBuilder_ == null) {
          return product_.get(index);  } else {
          return productBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .model.Product product = 1;</code>
       */
      public java.util.List<? extends br.example.demo.model.ProductProto.ProductOrBuilder> 
           getProductOrBuilderList() {
        if (productBuilder_ != null) {
          return productBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(product_);
        }
      }
      /**
       * <code>repeated .model.Product product = 1;</code>
       */
      public br.example.demo.model.ProductProto.Product.Builder addProductBuilder() {
        return getProductFieldBuilder().addBuilder(
            br.example.demo.model.ProductProto.Product.getDefaultInstance());
      }
      /**
       * <code>repeated .model.Product product = 1;</code>
       */
      public br.example.demo.model.ProductProto.Product.Builder addProductBuilder(
          int index) {
        return getProductFieldBuilder().addBuilder(
            index, br.example.demo.model.ProductProto.Product.getDefaultInstance());
      }
      /**
       * <code>repeated .model.Product product = 1;</code>
       */
      public java.util.List<br.example.demo.model.ProductProto.Product.Builder> 
           getProductBuilderList() {
        return getProductFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          br.example.demo.model.ProductProto.Product, br.example.demo.model.ProductProto.Product.Builder, br.example.demo.model.ProductProto.ProductOrBuilder> 
          getProductFieldBuilder() {
        if (productBuilder_ == null) {
          productBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              br.example.demo.model.ProductProto.Product, br.example.demo.model.ProductProto.Product.Builder, br.example.demo.model.ProductProto.ProductOrBuilder>(
                  product_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          product_ = null;
        }
        return productBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:model.Products)
    }

    // @@protoc_insertion_point(class_scope:model.Products)
    private static final br.example.demo.model.ProductProto.Products DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.example.demo.model.ProductProto.Products();
    }

    public static br.example.demo.model.ProductProto.Products getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Products>
        PARSER = new com.google.protobuf.AbstractParser<Products>() {
      @java.lang.Override
      public Products parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Products> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Products> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public br.example.demo.model.ProductProto.Products getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_Product_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_Product_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_Products_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_Products_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rproduct.proto\022\005model\032\033google/protobuf/" +
      "empty.proto\032\036google/protobuf/wrappers.pr" +
      "oto\"8\n\007Product\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t" +
      "\022\023\n\013description\030\003 \001(\t\"+\n\010Products\022\037\n\007pro" +
      "duct\030\001 \003(\0132\016.model.Product2\213\001\n\016ProductSe" +
      "rvice\0224\n\007FindAll\022\026.google.protobuf.Empty" +
      "\032\017.model.Products\"\000\022C\n\022FindOneProductByI" +
      "d\022\033.google.protobuf.Int32Value\032\016.model.P" +
      "roduct\"\000B%\n\025br.example.demo.modelB\014Produ" +
      "ctProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_model_Product_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_model_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_Product_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", });
    internal_static_model_Products_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_model_Products_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_Products_descriptor,
        new java.lang.String[] { "Product", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
