// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

// Protobuf Java Version: 3.25.1
package br.example.demo.model;

public final class CustomerProto {
  private CustomerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CustomerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.Customer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string document = 3;</code>
     * @return The document.
     */
    java.lang.String getDocument();
    /**
     * <code>string document = 3;</code>
     * @return The bytes for document.
     */
    com.google.protobuf.ByteString
        getDocumentBytes();
  }
  /**
   * Protobuf type {@code model.Customer}
   */
  public static final class Customer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.Customer)
      CustomerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Customer.newBuilder() to construct.
    private Customer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Customer() {
      name_ = "";
      document_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Customer();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.example.demo.model.CustomerProto.internal_static_model_Customer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.example.demo.model.CustomerProto.internal_static_model_Customer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.example.demo.model.CustomerProto.Customer.class, br.example.demo.model.CustomerProto.Customer.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOCUMENT_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object document_ = "";
    /**
     * <code>string document = 3;</code>
     * @return The document.
     */
    @java.lang.Override
    public java.lang.String getDocument() {
      java.lang.Object ref = document_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        document_ = s;
        return s;
      }
    }
    /**
     * <code>string document = 3;</code>
     * @return The bytes for document.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDocumentBytes() {
      java.lang.Object ref = document_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        document_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(document_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, document_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(document_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, document_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.example.demo.model.CustomerProto.Customer)) {
        return super.equals(obj);
      }
      br.example.demo.model.CustomerProto.Customer other = (br.example.demo.model.CustomerProto.Customer) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getDocument()
          .equals(other.getDocument())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DOCUMENT_FIELD_NUMBER;
      hash = (53 * hash) + getDocument().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.example.demo.model.CustomerProto.Customer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.example.demo.model.CustomerProto.Customer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.example.demo.model.CustomerProto.Customer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.example.demo.model.CustomerProto.Customer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.example.demo.model.CustomerProto.Customer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.example.demo.model.CustomerProto.Customer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.example.demo.model.CustomerProto.Customer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.example.demo.model.CustomerProto.Customer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static br.example.demo.model.CustomerProto.Customer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static br.example.demo.model.CustomerProto.Customer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.example.demo.model.CustomerProto.Customer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.example.demo.model.CustomerProto.Customer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.example.demo.model.CustomerProto.Customer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.Customer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.Customer)
        br.example.demo.model.CustomerProto.CustomerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.example.demo.model.CustomerProto.internal_static_model_Customer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.example.demo.model.CustomerProto.internal_static_model_Customer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.example.demo.model.CustomerProto.Customer.class, br.example.demo.model.CustomerProto.Customer.Builder.class);
      }

      // Construct using br.example.demo.model.CustomerProto.Customer.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        name_ = "";
        document_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.example.demo.model.CustomerProto.internal_static_model_Customer_descriptor;
      }

      @java.lang.Override
      public br.example.demo.model.CustomerProto.Customer getDefaultInstanceForType() {
        return br.example.demo.model.CustomerProto.Customer.getDefaultInstance();
      }

      @java.lang.Override
      public br.example.demo.model.CustomerProto.Customer build() {
        br.example.demo.model.CustomerProto.Customer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public br.example.demo.model.CustomerProto.Customer buildPartial() {
        br.example.demo.model.CustomerProto.Customer result = new br.example.demo.model.CustomerProto.Customer(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(br.example.demo.model.CustomerProto.Customer result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.document_ = document_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.example.demo.model.CustomerProto.Customer) {
          return mergeFrom((br.example.demo.model.CustomerProto.Customer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.example.demo.model.CustomerProto.Customer other) {
        if (other == br.example.demo.model.CustomerProto.Customer.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getDocument().isEmpty()) {
          document_ = other.document_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                document_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object document_ = "";
      /**
       * <code>string document = 3;</code>
       * @return The document.
       */
      public java.lang.String getDocument() {
        java.lang.Object ref = document_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          document_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string document = 3;</code>
       * @return The bytes for document.
       */
      public com.google.protobuf.ByteString
          getDocumentBytes() {
        java.lang.Object ref = document_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          document_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string document = 3;</code>
       * @param value The document to set.
       * @return This builder for chaining.
       */
      public Builder setDocument(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        document_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string document = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDocument() {
        document_ = getDefaultInstance().getDocument();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string document = 3;</code>
       * @param value The bytes for document to set.
       * @return This builder for chaining.
       */
      public Builder setDocumentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        document_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:model.Customer)
    }

    // @@protoc_insertion_point(class_scope:model.Customer)
    private static final br.example.demo.model.CustomerProto.Customer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.example.demo.model.CustomerProto.Customer();
    }

    public static br.example.demo.model.CustomerProto.Customer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Customer>
        PARSER = new com.google.protobuf.AbstractParser<Customer>() {
      @java.lang.Override
      public Customer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Customer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Customer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public br.example.demo.model.CustomerProto.Customer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CustomersOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.Customers)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .model.Customer customer = 1;</code>
     */
    java.util.List<br.example.demo.model.CustomerProto.Customer> 
        getCustomerList();
    /**
     * <code>repeated .model.Customer customer = 1;</code>
     */
    br.example.demo.model.CustomerProto.Customer getCustomer(int index);
    /**
     * <code>repeated .model.Customer customer = 1;</code>
     */
    int getCustomerCount();
    /**
     * <code>repeated .model.Customer customer = 1;</code>
     */
    java.util.List<? extends br.example.demo.model.CustomerProto.CustomerOrBuilder> 
        getCustomerOrBuilderList();
    /**
     * <code>repeated .model.Customer customer = 1;</code>
     */
    br.example.demo.model.CustomerProto.CustomerOrBuilder getCustomerOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code model.Customers}
   */
  public static final class Customers extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.Customers)
      CustomersOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Customers.newBuilder() to construct.
    private Customers(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Customers() {
      customer_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Customers();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.example.demo.model.CustomerProto.internal_static_model_Customers_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.example.demo.model.CustomerProto.internal_static_model_Customers_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.example.demo.model.CustomerProto.Customers.class, br.example.demo.model.CustomerProto.Customers.Builder.class);
    }

    public static final int CUSTOMER_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<br.example.demo.model.CustomerProto.Customer> customer_;
    /**
     * <code>repeated .model.Customer customer = 1;</code>
     */
    @java.lang.Override
    public java.util.List<br.example.demo.model.CustomerProto.Customer> getCustomerList() {
      return customer_;
    }
    /**
     * <code>repeated .model.Customer customer = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends br.example.demo.model.CustomerProto.CustomerOrBuilder> 
        getCustomerOrBuilderList() {
      return customer_;
    }
    /**
     * <code>repeated .model.Customer customer = 1;</code>
     */
    @java.lang.Override
    public int getCustomerCount() {
      return customer_.size();
    }
    /**
     * <code>repeated .model.Customer customer = 1;</code>
     */
    @java.lang.Override
    public br.example.demo.model.CustomerProto.Customer getCustomer(int index) {
      return customer_.get(index);
    }
    /**
     * <code>repeated .model.Customer customer = 1;</code>
     */
    @java.lang.Override
    public br.example.demo.model.CustomerProto.CustomerOrBuilder getCustomerOrBuilder(
        int index) {
      return customer_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < customer_.size(); i++) {
        output.writeMessage(1, customer_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < customer_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, customer_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.example.demo.model.CustomerProto.Customers)) {
        return super.equals(obj);
      }
      br.example.demo.model.CustomerProto.Customers other = (br.example.demo.model.CustomerProto.Customers) obj;

      if (!getCustomerList()
          .equals(other.getCustomerList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCustomerCount() > 0) {
        hash = (37 * hash) + CUSTOMER_FIELD_NUMBER;
        hash = (53 * hash) + getCustomerList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.example.demo.model.CustomerProto.Customers parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.example.demo.model.CustomerProto.Customers parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.example.demo.model.CustomerProto.Customers parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.example.demo.model.CustomerProto.Customers parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.example.demo.model.CustomerProto.Customers parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.example.demo.model.CustomerProto.Customers parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.example.demo.model.CustomerProto.Customers parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.example.demo.model.CustomerProto.Customers parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static br.example.demo.model.CustomerProto.Customers parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static br.example.demo.model.CustomerProto.Customers parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.example.demo.model.CustomerProto.Customers parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.example.demo.model.CustomerProto.Customers parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.example.demo.model.CustomerProto.Customers prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.Customers}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.Customers)
        br.example.demo.model.CustomerProto.CustomersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.example.demo.model.CustomerProto.internal_static_model_Customers_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.example.demo.model.CustomerProto.internal_static_model_Customers_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.example.demo.model.CustomerProto.Customers.class, br.example.demo.model.CustomerProto.Customers.Builder.class);
      }

      // Construct using br.example.demo.model.CustomerProto.Customers.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (customerBuilder_ == null) {
          customer_ = java.util.Collections.emptyList();
        } else {
          customer_ = null;
          customerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.example.demo.model.CustomerProto.internal_static_model_Customers_descriptor;
      }

      @java.lang.Override
      public br.example.demo.model.CustomerProto.Customers getDefaultInstanceForType() {
        return br.example.demo.model.CustomerProto.Customers.getDefaultInstance();
      }

      @java.lang.Override
      public br.example.demo.model.CustomerProto.Customers build() {
        br.example.demo.model.CustomerProto.Customers result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public br.example.demo.model.CustomerProto.Customers buildPartial() {
        br.example.demo.model.CustomerProto.Customers result = new br.example.demo.model.CustomerProto.Customers(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(br.example.demo.model.CustomerProto.Customers result) {
        if (customerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            customer_ = java.util.Collections.unmodifiableList(customer_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.customer_ = customer_;
        } else {
          result.customer_ = customerBuilder_.build();
        }
      }

      private void buildPartial0(br.example.demo.model.CustomerProto.Customers result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.example.demo.model.CustomerProto.Customers) {
          return mergeFrom((br.example.demo.model.CustomerProto.Customers)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.example.demo.model.CustomerProto.Customers other) {
        if (other == br.example.demo.model.CustomerProto.Customers.getDefaultInstance()) return this;
        if (customerBuilder_ == null) {
          if (!other.customer_.isEmpty()) {
            if (customer_.isEmpty()) {
              customer_ = other.customer_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCustomerIsMutable();
              customer_.addAll(other.customer_);
            }
            onChanged();
          }
        } else {
          if (!other.customer_.isEmpty()) {
            if (customerBuilder_.isEmpty()) {
              customerBuilder_.dispose();
              customerBuilder_ = null;
              customer_ = other.customer_;
              bitField0_ = (bitField0_ & ~0x00000001);
              customerBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCustomerFieldBuilder() : null;
            } else {
              customerBuilder_.addAllMessages(other.customer_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                br.example.demo.model.CustomerProto.Customer m =
                    input.readMessage(
                        br.example.demo.model.CustomerProto.Customer.parser(),
                        extensionRegistry);
                if (customerBuilder_ == null) {
                  ensureCustomerIsMutable();
                  customer_.add(m);
                } else {
                  customerBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<br.example.demo.model.CustomerProto.Customer> customer_ =
        java.util.Collections.emptyList();
      private void ensureCustomerIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          customer_ = new java.util.ArrayList<br.example.demo.model.CustomerProto.Customer>(customer_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          br.example.demo.model.CustomerProto.Customer, br.example.demo.model.CustomerProto.Customer.Builder, br.example.demo.model.CustomerProto.CustomerOrBuilder> customerBuilder_;

      /**
       * <code>repeated .model.Customer customer = 1;</code>
       */
      public java.util.List<br.example.demo.model.CustomerProto.Customer> getCustomerList() {
        if (customerBuilder_ == null) {
          return java.util.Collections.unmodifiableList(customer_);
        } else {
          return customerBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .model.Customer customer = 1;</code>
       */
      public int getCustomerCount() {
        if (customerBuilder_ == null) {
          return customer_.size();
        } else {
          return customerBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .model.Customer customer = 1;</code>
       */
      public br.example.demo.model.CustomerProto.Customer getCustomer(int index) {
        if (customerBuilder_ == null) {
          return customer_.get(index);
        } else {
          return customerBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .model.Customer customer = 1;</code>
       */
      public Builder setCustomer(
          int index, br.example.demo.model.CustomerProto.Customer value) {
        if (customerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomerIsMutable();
          customer_.set(index, value);
          onChanged();
        } else {
          customerBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .model.Customer customer = 1;</code>
       */
      public Builder setCustomer(
          int index, br.example.demo.model.CustomerProto.Customer.Builder builderForValue) {
        if (customerBuilder_ == null) {
          ensureCustomerIsMutable();
          customer_.set(index, builderForValue.build());
          onChanged();
        } else {
          customerBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.Customer customer = 1;</code>
       */
      public Builder addCustomer(br.example.demo.model.CustomerProto.Customer value) {
        if (customerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomerIsMutable();
          customer_.add(value);
          onChanged();
        } else {
          customerBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .model.Customer customer = 1;</code>
       */
      public Builder addCustomer(
          int index, br.example.demo.model.CustomerProto.Customer value) {
        if (customerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomerIsMutable();
          customer_.add(index, value);
          onChanged();
        } else {
          customerBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .model.Customer customer = 1;</code>
       */
      public Builder addCustomer(
          br.example.demo.model.CustomerProto.Customer.Builder builderForValue) {
        if (customerBuilder_ == null) {
          ensureCustomerIsMutable();
          customer_.add(builderForValue.build());
          onChanged();
        } else {
          customerBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.Customer customer = 1;</code>
       */
      public Builder addCustomer(
          int index, br.example.demo.model.CustomerProto.Customer.Builder builderForValue) {
        if (customerBuilder_ == null) {
          ensureCustomerIsMutable();
          customer_.add(index, builderForValue.build());
          onChanged();
        } else {
          customerBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.Customer customer = 1;</code>
       */
      public Builder addAllCustomer(
          java.lang.Iterable<? extends br.example.demo.model.CustomerProto.Customer> values) {
        if (customerBuilder_ == null) {
          ensureCustomerIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, customer_);
          onChanged();
        } else {
          customerBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .model.Customer customer = 1;</code>
       */
      public Builder clearCustomer() {
        if (customerBuilder_ == null) {
          customer_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          customerBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .model.Customer customer = 1;</code>
       */
      public Builder removeCustomer(int index) {
        if (customerBuilder_ == null) {
          ensureCustomerIsMutable();
          customer_.remove(index);
          onChanged();
        } else {
          customerBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .model.Customer customer = 1;</code>
       */
      public br.example.demo.model.CustomerProto.Customer.Builder getCustomerBuilder(
          int index) {
        return getCustomerFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .model.Customer customer = 1;</code>
       */
      public br.example.demo.model.CustomerProto.CustomerOrBuilder getCustomerOrBuilder(
          int index) {
        if (customerBuilder_ == null) {
          return customer_.get(index);  } else {
          return customerBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .model.Customer customer = 1;</code>
       */
      public java.util.List<? extends br.example.demo.model.CustomerProto.CustomerOrBuilder> 
           getCustomerOrBuilderList() {
        if (customerBuilder_ != null) {
          return customerBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(customer_);
        }
      }
      /**
       * <code>repeated .model.Customer customer = 1;</code>
       */
      public br.example.demo.model.CustomerProto.Customer.Builder addCustomerBuilder() {
        return getCustomerFieldBuilder().addBuilder(
            br.example.demo.model.CustomerProto.Customer.getDefaultInstance());
      }
      /**
       * <code>repeated .model.Customer customer = 1;</code>
       */
      public br.example.demo.model.CustomerProto.Customer.Builder addCustomerBuilder(
          int index) {
        return getCustomerFieldBuilder().addBuilder(
            index, br.example.demo.model.CustomerProto.Customer.getDefaultInstance());
      }
      /**
       * <code>repeated .model.Customer customer = 1;</code>
       */
      public java.util.List<br.example.demo.model.CustomerProto.Customer.Builder> 
           getCustomerBuilderList() {
        return getCustomerFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          br.example.demo.model.CustomerProto.Customer, br.example.demo.model.CustomerProto.Customer.Builder, br.example.demo.model.CustomerProto.CustomerOrBuilder> 
          getCustomerFieldBuilder() {
        if (customerBuilder_ == null) {
          customerBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              br.example.demo.model.CustomerProto.Customer, br.example.demo.model.CustomerProto.Customer.Builder, br.example.demo.model.CustomerProto.CustomerOrBuilder>(
                  customer_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          customer_ = null;
        }
        return customerBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:model.Customers)
    }

    // @@protoc_insertion_point(class_scope:model.Customers)
    private static final br.example.demo.model.CustomerProto.Customers DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.example.demo.model.CustomerProto.Customers();
    }

    public static br.example.demo.model.CustomerProto.Customers getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Customers>
        PARSER = new com.google.protobuf.AbstractParser<Customers>() {
      @java.lang.Override
      public Customers parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Customers> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Customers> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public br.example.demo.model.CustomerProto.Customers getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_Customer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_Customer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_Customers_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_Customers_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016customer.proto\022\005model\032\033google/protobuf" +
      "/empty.proto\032\036google/protobuf/wrappers.p" +
      "roto\"6\n\010Customer\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001" +
      "(\t\022\020\n\010document\030\003 \001(\t\".\n\tCustomers\022!\n\010cus" +
      "tomer\030\001 \003(\0132\017.model.Customer2H\n\017Customer" +
      "Service\0225\n\007FindAll\022\026.google.protobuf.Emp" +
      "ty\032\020.model.Customers\"\000B&\n\025br.example.dem" +
      "o.modelB\rCustomerProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_model_Customer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_model_Customer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_Customer_descriptor,
        new java.lang.String[] { "Id", "Name", "Document", });
    internal_static_model_Customers_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_model_Customers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_Customers_descriptor,
        new java.lang.String[] { "Customer", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
